# Cấu hình hệ thống
app_settings:
  port: 9999
  name: "SECommerce-Recommender"
  middleware:
    # Có thể dùng chỉ cho phép đường dẫn được chỉ định để yêu cầu tới API
    origins: ["*"]

    # Có yêu cầu chứng chỉ
    credentials: true

    # Các phương thức được cho phép sử dụng
    methods: ["*"]

    # Các dạng headers được cho phép
    headers: ["*"]

# Cấu hình Redis dành cho việc tối ưu hóa các truy vấn đến từ database
redis:
  host: "venndev.redis.cache.windows.net"
  port: 6380
  password: "VJTLTIg1q8KuZ0VcIStMGfPoRpEbavifLAzCaBCNufQ="
  ssl: true

# Cấu hình database
# Chỉ hỗ trợ MySQL
database:
  host: "venndev.mysql.database.azure.com"
  port: 3306
  user: "sql12749417"
  password: "xsgyeANBRZ@@@"
  name: "shop"
  ssl_verify_cert: false

# Cấu hình hệ thống gợi ý
system:
  recommend:

    # Cấu hình gợi ý tìm kiếm dành cho người dùng
    search_hint:
      key_redis: "search_hint_cache"
      name_table_target: "product"
      columns_target:
        - "title"
      column_key: "title"

      # Số lượng cần gợi ý tối đa
      limit: 5

      # Số điểm đánh giá gần giống
      score_cutoff: 50

    # Cấu hình gợi ý theo loại sản phẩm
    recommend_like_category:
      key_redis: "recommend_like_category_cache"
      name_table_target: "product"
      columns_target:
        - "id"
        - "categoryId"
      column_key: "categoryId"

      # Số lượng cần gợi ý tối đa
      limit: 5

      # Số điểm đánh giá gần giống
      score_cutoff: 30