services:
  ec-api:
    container_name: ec-api
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: 'on-failure'
    ports:
      - 9999:9999

  prometheus:
    image: prom/prometheus:latest
    restart: 'always'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'