version: "3"
services:
  ec-api:
    container_name: ec-api
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: "on-failure"
    ports:
      - 9999:9999
    volumes:
      - ./logs:/logs

  prometheus:
    image: prom/prometheus:latest
    restart: "always"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
